// import Navbar from "@/components/componentKu/Navbar";
import HeaderMain from "@/components/components/HeaderMain";
import HeaderTop from "@/components/components/HeaderTop";
import MobNavbar from "@/components/components/MobNavbar";
// import Navbar from "@/components/components/Navbar";
import Sidebar, { SidebarItem } from "@/components/sidebarku";
import "./globals.css";
import {
  BarChart3,
  Boxes,
  LayoutDashboard,
  Settings,
  UserCircle,
} from "lucide-react";
import { Session } from "next-auth";
import { Inter } from "next/font/google";
import { Metadata } from "next";
import Navbar from "@/components/componentKu/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pustaka Online",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode;
  session: Session;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <HeaderTop />
        <Navbar />
        <MobNavbar />
        {children}
      </body>
    </html>
  );
}
