import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReactQuery from "@/components/ReactQuery";
import NextAuthProvider from "@/components/NextAuthProvider";
import { Session } from "next-auth";
import LoadingPage from "@/components/LoadingPage";
import Navbar from "@/components/componentKu/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode;
  session: Session;
}) {
  return (
    <html lang="en">
      <body className="">
        <NextAuthProvider session={session}>
          <ReactQuery>

            <LoadingPage>
            {/* <Navbar /> */}
              
              {children}
              </LoadingPage>
          </ReactQuery>
        </NextAuthProvider>
      </body>
    </html>
  );
}
