"use client";
import Navbar from "@/components/componentKu/Navbar";
import Footer from "@/components/componentKu/footer";
import HeaderTop from "@/components/components/HeaderTop";
import MobNavbar from "@/components/components/MobNavbar";
import clsx from "clsx";
import { Metadata } from "next";
import { Session } from "next-auth";
import { Inter } from "next/font/google";
import Link from "next/link";
import { useRouter, usePathname } from "next/navigation";

import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pustaka Online",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode;
  session: Session;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderTop />
        <Navbar />
        <MobNavbar />
        {children}
        <Footer/> 
      </body>
    </html>
  );
}
