// import Navbar from "@/components/componentKu/Navbar";
import HeaderMain from "@/components/components/HeaderMain";
import HeaderTop from "@/components/components/HeaderTop";
import MobNavbar from "@/components/components/MobNavbar";
// import Navbar from "@/components/components/Navbar";
import Sidebar, { SidebarItem } from "@/components/sidebarku";
import "./globals.css";
import {
  BarChart3,
  Boxes,
  LayoutDashboard,
  Settings,
  UserCircle,
} from "lucide-react";
import { Session } from "next-auth";
import { Inter } from "next/font/google";
import { Metadata } from "next";
import Navbar from "@/components/componentKu/Navbar";
import Footer from "@/components/componentKu/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pustaka Online",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode;
  session: Session;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Sidebar >
      <SidebarItem icon={<LayoutDashboard size={20}/>} text={'DashBoard'} alert/>
      <SidebarItem icon={<BarChart3 size={20}/>} text={'DashBoard'} alert/>
      <SidebarItem icon={<UserCircle size={20}/>} text={'Users'} alert/>
      <SidebarItem icon={<Boxes size={20}/>} text={'Inventory'} alert/>
      <hr  className="my-3"/>
      <SidebarItem icon={<Settings size={20}/>} text={'Setting'} alert/>
      </Sidebar> */}
        <HeaderTop />
        <Navbar />
        {/* <HeaderMain/> */}
        <MobNavbar />
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
